# Generated by Django 2.1.7 on 2019-03-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_organizationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizationid',
            field=models.ForeignKey(db_column='OrganizationID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Organization'),
        ),
    ]
