# Generated by Django 2.1.7 on 2019-03-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organizationid',
        ),
    ]
