# Generated by Django 2.1.7 on 2019-03-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190306_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizationid',
            field=models.ForeignKey(db_column='OrganizationID', default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.ManyToManyField(to='Users.Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_column='UserName', max_length=255, null=True, unique=True),
        ),
    ]
