# Generated by Django 2.1.7 on 2019-03-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('groupname', models.CharField(blank=True, db_column='GroupName', max_length=255, null=True, unique=True)),
                ('creationdate', models.DateField(blank=True, db_column='CreationDate', null=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.CharField(db_column='Description', max_length=255)),
            ],
            options={
                'db_table': 'Group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('patternname', models.CharField(db_column='PatternName', max_length=255)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('data_creation', models.DateField(db_column='Data Creation')),
            ],
            options={
                'db_table': 'Pattern',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sentencename', models.CharField(db_column='SentenceName', max_length=255)),
                ('datecreated', models.DateField(db_column='DateCreated')),
                ('subject', models.CharField(db_column='Subject', max_length=255)),
                ('receiver', models.CharField(blank=True, db_column='Receiver', max_length=255, null=True)),
                ('datarealizado', models.DateField(db_column='DataRealizado')),
                ('artefacto', models.CharField(db_column='Artefacto', max_length=255)),
                ('group', models.ManyToManyField(to='Activities.Group')),
            ],
            options={
                'db_table': 'Sentence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.IntegerField(blank=True, db_column='Name', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('verbname', models.CharField(db_column='VerbName', max_length=255, unique=True)),
                ('verbtype', models.CharField(db_column='VerbType', max_length=255)),
            ],
            options={
                'db_table': 'Verb',
                'managed': True,
            },
        ),
    ]
