# Generated by Django 2.1.7 on 2019-06-24 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='image',
        ),
        migrations.AddField(
            model_name='artefact',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verb',
            name='datecreated',
            field=models.DateField(blank=True, db_column='DateCreated', null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
