# Generated by Django 2.1.7 on 2019-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_auto_20190319_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='artefacto',
            field=models.CharField(db_column='Artefacto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='datarealizado',
            field=models.DateField(db_column='DataRealizado', null=True),
        ),
    ]
