# Generated by Django 2.1.7 on 2019-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20190319_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='data_creation',
            field=models.DateField(db_column='Data Creation', null=True),
        ),
    ]
