# Generated by Django 2.1.7 on 2019-06-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20190624_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(db_column='Description'),
        ),
    ]
