# Generated by Django 2.1.7 on 2019-03-16 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Activities', '0002_auto_20190306_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('activityname', models.CharField(blank=True, db_column='ActivityName', max_length=255, null=True)),
                ('descriçào', models.CharField(blank=True, db_column='Descriçào', max_length=255, null=True)),
                ('pattern', models.ManyToManyField(to='Activities.Pattern')),
            ],
            options={
                'db_table': 'Activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('processname', models.CharField(blank=True, db_column='ProcessName', max_length=255, null=True)),
                ('data_criação', models.DateField(db_column='Data Criação')),
                ('descrição', models.CharField(db_column='Descrição', max_length=255)),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Process',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=255, null=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=1)),
                ('formato', models.CharField(db_column='Formato', max_length=255)),
                ('activity', models.ManyToManyField(to='Processes.Activity')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, db_column='RoleName', max_length=255, null=True)),
                ('product', models.ManyToManyField(to='Processes.Product')),
            ],
            options={
                'db_table': 'Role',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='processid',
            field=models.ForeignKey(db_column='ProcessID', on_delete=django.db.models.deletion.DO_NOTHING, to='Processes.Process'),
        ),
        migrations.AddField(
            model_name='activity',
            name='role',
            field=models.ManyToManyField(to='Processes.Role'),
        ),
    ]
