# Generated by Django 2.1.7 on 2019-03-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Processes', '0002_process_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True},
        ),
    ]
